name: image_deduplicator
channels:
    - conda-forge
    - defaults
dependencies:
    - pip=24.0
    - pip:
      - opencv-contrib-python==4.6.0.66
      - numpy==1.26.4
      - scipy==1.13.1
      - pillow==10.3.0
      - pytest==8.2.2 